apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # 名字必需与下面的 spec 字段匹配，并且格式为'<Resource 名称的复数形式>.<组名>'
  name: demos.example.com
spec:
  # 组名称，用于 REST API: '/apis/<组名>/<版本>'
  group: example.com
  names:
    # 名称的复数形式，用于 URL：/apis/<组名>/<版本>/<名称的复数形式>
    plural: demos
    # 名称的单数形式，作为命令行使用时和显示时的别名
    singular: demo
    # kind 通常是单数形式的帕斯卡编码（PascalCased）形式。你的资源清单会使用这一形式
    kind: Demo
    # shortNames 允许你在命令行上使用较短的字符串来匹配资源
    shortNames:
      - dm
  # 可以是 NameSpaced、Cluster 或 Both，（但是常用的是 NameSpaced 或 Cluster）
  scope: Namespaced
  # 列举此 CustomResourceDefinition 所支持的 API 版本
  versions:
    - name: v1
      # 每个版本都可以通过 served 标志来独立启用或者禁止（每个版本都有一个单独的、唯一的名称）
      served: true # 启用，false 则为禁用
      # 其中一个并且只有一个版本必需被标记为存储版本（存储到 Etcd 数据库中）
      storage: true
      # 自定义资源属性定义
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  pattern: '^test$'
      additionalPrinterColumns:
        - name: CR-Name
          type: string
          description: "The name of resource"
          jsonPath: .spec.name