# ingress-manager-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ingress-manager
  name: ingress-manager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-manager
  template:
    metadata:
      labels:
        app: ingress-manager
    spec:
      # 需要关联 ServiceAccount
      serviceAccountName: ingress-manager-sa
      containers:
        - image: dragonzw/ingress-manager:1.0.0
          name: ingress-manager
          resources: {}