# ingress-manager-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ingress-manager-role
  namespace: default
rules:
  - apiGroups:
      - ""
    # 将 Service 的权限进行回收
    resources:
      - services
    verbs:
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - list
      - watch
      - create
      - update
      - delete